<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260119194846 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ranking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_80B839D07E3C61F9 ON ranking (owner_id)');
        $this->addSql('CREATE TABLE ranking_element (ranking_id INT NOT NULL, element_id INT NOT NULL, PRIMARY KEY (ranking_id, element_id))');
        $this->addSql('CREATE INDEX IDX_4991085320F64684 ON ranking_element (ranking_id)');
        $this->addSql('CREATE INDEX IDX_499108531F1F2A24 ON ranking_element (element_id)');
        $this->addSql('CREATE TABLE rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, comment TEXT DEFAULT NULL, owner_id INT NOT NULL, element_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D88926227E3C61F9 ON rating (owner_id)');
        $this->addSql('CREATE INDEX IDX_D88926221F1F2A24 ON rating (element_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_80B839D07E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ranking_element ADD CONSTRAINT FK_4991085320F64684 FOREIGN KEY (ranking_id) REFERENCES ranking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ranking_element ADD CONSTRAINT FK_499108531F1F2A24 FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D88926227E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D88926221F1F2A24 FOREIGN KEY (element_id) REFERENCES element (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ranking DROP CONSTRAINT FK_80B839D07E3C61F9');
        $this->addSql('ALTER TABLE ranking_element DROP CONSTRAINT FK_4991085320F64684');
        $this->addSql('ALTER TABLE ranking_element DROP CONSTRAINT FK_499108531F1F2A24');
        $this->addSql('ALTER TABLE rating DROP CONSTRAINT FK_D88926227E3C61F9');
        $this->addSql('ALTER TABLE rating DROP CONSTRAINT FK_D88926221F1F2A24');
        $this->addSql('DROP TABLE ranking');
        $this->addSql('DROP TABLE ranking_element');
        $this->addSql('DROP TABLE rating');
    }
}
