<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260216182717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_ranking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, owner_id INT NOT NULL, element_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8B527DA7E3C61F9 ON user_ranking (owner_id)');
        $this->addSql('CREATE INDEX IDX_D8B527DA1F1F2A24 ON user_ranking (element_id)');
        $this->addSql('CREATE INDEX IDX_D8B527DA12469DE2 ON user_ranking (category_id)');
        $this->addSql('ALTER TABLE user_ranking ADD CONSTRAINT FK_D8B527DA7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_ranking ADD CONSTRAINT FK_D8B527DA1F1F2A24 FOREIGN KEY (element_id) REFERENCES element (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_ranking ADD CONSTRAINT FK_D8B527DA12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_ranking DROP CONSTRAINT FK_D8B527DA7E3C61F9');
        $this->addSql('ALTER TABLE user_ranking DROP CONSTRAINT FK_D8B527DA1F1F2A24');
        $this->addSql('ALTER TABLE user_ranking DROP CONSTRAINT FK_D8B527DA12469DE2');
        $this->addSql('DROP TABLE user_ranking');
    }
}
